stages:
  - module-pipelines

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend # depend нужен, если какой-нибудь дочерний пайплайн свалился, мы знали, что общий пайплайн тоже идёт с ошибкой
  only:
    changes: # как только происходит изменение в папке frontend, запускается дочерний пайплайн, который лежит в этой папке
      - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:  # как только происходит изменение в папке backend, запускается дочерний пайплайн, который лежит в этой папке
      - backend/**/*

terraform:
  stage: module-pipelines
  trigger:
    include:
      - "/infrastructure/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:  # как только происходит изменение в папке infrastructure, запускается дочерний пайплайн, который лежит в этой папке
      - infrastructure/**/*

kubernetes:
  stage: module-pipelines
  trigger:
    include:
      - "/kubernetes/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:  # как только происходит изменение в папке kubernetes, запускается дочерний пайплайн, который лежит в этой папке
      - kubernetes/**/*
  allow_failure: true

helm-chart:
  stage: module-pipelines
  trigger:
    include:
      - "/momo-store-chart/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:  # как только происходит изменение в папке momo-store-chart, запускается дочерний пайплайн, который лежит в этой папке
      - momo-store-chart/**/*

monitoring:
  stage: module-pipelines
  trigger:
    include:
      - "/monitoring/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:  # как только происходит изменение в папке monitoring, запускается дочерний пайплайн, который лежит в этой папке
      - monitoring/**/*