---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  revisionHistoryLimit: 12
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    # шаблон для создания Pod'ов
    spec:
      containers:
      - image: gitlab.praktikum-services.ru:5050/std-028-16/momo-store/momo-backend:1.0.1472019
        name: backend
        imagePullPolicy: IfNotPresent
        env:
        - name: REPORT_PATH
          value: "/var/www-data/htdocs"  
        ports:
        - name: backend
          containerPort: 8081
        livenessProbe:
          # проверка живучести выполнит запрос HTTP GET       
          httpGet:
            # путь к запросу в HTTP-запросе          
            path: /health
            # порт, к которому должна подключиться проверка        
            port: 8081
          # перед исполнением первой проверки подождать 15 секунд, пока стартанёт бэкенд          
          initialDelaySeconds: 15
          # период выполнения проверки
          periodSeconds: 30
          # максимальное время выполнения проверки (по умолчанию 1 раз)
          timeoutSeconds: 2
          # сколько раз пробовать попытку, если она провалилась (по умолчанию 1 раз)
          failureThreshold: 6
      # чтобы Кубер мог скачивать образы из нашего GitLab Registry
      imagePullSecrets:
      - name: gitlab-cr-secret