# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-cr-secret
data:
    .dockerconfigjson: >-
        ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoic3RkLTAyOC0xNiIsCiAgICAgICAgICAgICJwYXNzd29yZCI6Im8zQTI5MWdCIiwKICAgICAgICAgICAgImF1dGgiOiJjM1JrTFRBeU9DMHhOanB2TTBFeU9URm5RZz09IgogICAgICAgIH0KICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson