---
# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-cr-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: >-
    {{ .Values.CR_SECRET }}
type: kubernetes.io/dockerconfigjson
