apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: momo-back
  namespace: default
  labels:
    prometheus: pod
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
  - path: /metrics
    port: backend
